default_install_hook_types: [pre-commit]
default_stages: [pre-commit]
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: check-json
        -   id: pretty-format-json
            args: [--no-sort-keys, --autofix, --no-ensure-ascii]
        -   id: check-merge-conflict
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  - repo: local
    hooks:
      -   id: prettier
          name: Prettier
          entry: node_modules/.bin/prettier --write --config .prettierrc
          language: node
          files: (\.js|\.jsx|\.ts|\.tsx)$
  - repo: local
    hooks:
      -   id: eslint
          name: ES Lint
          entry: node_modules/.bin/eslint -c eslint.config.mjs --fix
          language: node
          files: (\.js|\.jsx|\.ts|\.tsx)$
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: npx tsc --noEmit --project tsconfig.json
        language: node
        pass_filenames: false
  - repo: local
    hooks:
      - id: tests
        name: Tests
        entry: npm run test
        language: node
        pass_filenames: false
