services:
  local_db:
    image: mysql:latest
    container_name: paladin-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paladin_technical_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/paladin_technical_test_dump.sql:/docker-entrypoint-initdb.d/paladin_technical_test_dump.sql

volumes:
  mysql_data:
